</td></tr>
</table>

<br>
<center>
<table border="0" cellpadding="0" cellspacing="0">
<tr>
<td><A HREF="http://forum.astrive.ru/"><img src="img/forum_logo.gif" alt="FORUM logo" border=0 width=90 height=36></a></td>
<td>&nbsp;<b>powered by</b>&nbsp;</td>
<td><A href="http://www.php.net"><img src="img/php_logo.gif" alt="PHP logo" border=0 width=96 height=50 valign=top></a></td>
<td>&nbsp;<b>&amp;</b>&nbsp;&nbsp;</td>
<td><A href="http://www.mysql.org"><img src="img/mysql_logo.gif" alt="MySQL logo" border=0 width=88 height=31></a></td>
</tr>
</table>
</center>

</body>
</html>
