<html>
<head>
<title>FORUM</title>

<LINK REL=STYLESHEET TYPE="text/css" HREF="forum_styles.css">

</head>

<body> 

<table width="90%" align="center" border="0" cellpadding="0" cellspacing="0">
<tr><td>

<h2>PHP/MySQL Forum</h2>

<table width="50%" border="0" cellpadding="0" cellspacing="0">
<tr>
    <td>
Information:
<br>
<a href="README.md">README</a>
<br>
<a href="ChangeLog">ChangeLog</a>
<br>
    </td>
</tr>
</table>

<center><h3>Forum</h3></center>
<a href="admin.php">Administration</a> (login: admin, password: change_it)

