<?

$msg["author"] = "Autorius";
$msg["date"]   = "Data";
$msg["subject"]   = "Pavadinimas";

$msg["msg_text"]  = "Tekstas";
$msg["send_msg"] = "Siшsti skelbimа";
$msg["reset_msg"] = "Iрtrinti skelbimа";
$msg["orig_msg_text"] = "Cituoti originalа";
$msg["cancel"] = " Atрaukti ";

$msg["new_thread"] = "Sukurti skelbimа naujoje рakoje";
$msg["your_msg_new_subject"] = "Jыsш skelbimas";
$msg["your_msg_on_subject"] = "Jыsш skelbimas рakoje ";

$msg["close_win"] = "Uюdaryti langа";
$msg["full_list"] = "Visi skelbimai";

$msg["continue_thread"] = "Atsakyti";
$msg["open_subthread"]  = "Sukurti poрakб";

$msg["name"] = "Jыsш vardas";
$msg["enter_name"] = "Praрome бvesti savo vardа";
$msg["enter_subj"] = "Praрome бvesti skelbimo pavadinimа";

$msg["view_article"] = "Paюiыrлti skelbimа";

$msg["all"] = "all";
$msg["view_articles_for_last"] = "Paюiыrлti tokio senumo skelbimus";
$msg["days"] = "dienш";
$msg["go"] = " Eiti ";

$msg["all_articles"] = "Visi skelbimai";

$msg["remote_host"] = "Vartotojo hostas";
$msg["remote_addr"] = "Vartotojo IP adresas";
$msg["proxy_addr"]  = "Adresas uю proxy";

$msg["search"] = "Rasti";

$msg["any"] = "bet kokб";
$msg["all"] = "visus";
$msg["exact"] = "tiksliai";
$msg["keywords"] = "Paieрkos юodюiai";

$msg["tot_found"] = "Iр viso rasta бraрш";

$msg["stats"] = "Statistika";
$msg["noread"] = "Niekas dar neskaitл";

$msg["ch_timeframe"] = "Pakeisti laikа";
$msg["st_date"] = "Pradюios data";
$msg["en_date"] = "Pabaigos data";
$msg["tot_vis"] = "Iр viso skaitytojш";
$msg["host"] = "Hostas";
$msg["date_visit"] = "Data";

$msg["back"] = "Atgal";

$msg["views"] = "Perюiыros";

$msg["all_thread_articles"] = "Matyti visus skelbimus рakoje";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>