<?php

$msg["author"] = "Kirjoittaja";
$msg["date"]   = "Päiväys";
$msg["subject"]   = "Otsikko";

$msg["msg_text"]  = "Viestin sisältö";
$msg["send_msg"] = "Lähetä";
$msg["reset_msg"] = "Tyhjennä";
$msg["orig_msg_text"] = "Lainaa lukemasi viestin teksti";
$msg["cancel"] = " Peruuta ";

$msg["new_thread"] = "Aloita uusi keskustelu";
$msg["your_msg_new_subject"] = "Vastaa tähän viestiin";
$msg["your_msg_on_subject"] = "Vastaa tämän aiheen ensimmäiseen viestiin";

$msg["close_win"] = "Sulje ikkuna";
$msg["full_list"] = "Takaisin foorumin etusivulle";

$msg["continue_thread"] = "Vastaa aiheen ensimmäiseen";
$msg["open_subthread"]  = "Vastaa juuri lukemaasi";

$msg["name"] = "Nimesi";
$msg["enter_name"] = "Kirjoita nimesi";
$msg["enter_subj"] = "Kirjoita viestillesi otsikko";

$msg["view_article"] = "Näytä viesti";

$msg["all"] = "kaikki";
$msg["view_articles_for_last"] = "Näytä viimeiset";
$msg["days"] = "päivää";
$msg["go"] = " Hae ";

$msg["all_articles"] = "Takaisin foorumin etusivulle";

$msg["remote_host"] = "Etäkone";
$msg["remote_addr"] = "Etäkoneen IP";
$msg["proxy_addr"]  = "Proxyn osoite";

$msg["search"] = "Etsi";

$msg["any"] = "Joku (any)";
$msg["all"] = "Kaikki (all)";
$msg["exact"] = "Täsmälleen (exact)";
$msg["keywords"] = "Hakutapa";

$msg["tot_found"] = "Tuloksia tuli";

$msg["stats"] = "Tilastot";
$msg["noread"] = "Kukaan ei ole lukenut";

$msg["ch_timeframe"] = "Vaihda aikajaksoa";
$msg["st_date"] = "Aloitus PVM";
$msg["en_date"] = "Lopetus PVM";
$msg["tot_vis"] = "Vierailuja yhteensä";
$msg["host"] = "Kone";
$msg["date_visit"] = "Vierailu PVM";

$msg["back"] = "Takaisin";

$msg["views"] = "Näkymät";

$msg["all_thread_articles"] = "Näytä tämän keskusteluaiheen kaikki viestit";
$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>