<?

$msg["author"] = "作者";
$msg["date"]   = "日期";
$msg["subject"]   = "標題";

$msg["msg_text"]  = "內容";
$msg["send_msg"] = "送出";
$msg["reset_msg"] = "清除";
$msg["orig_msg_text"] = "引用原始內容";
$msg["cancel"] = " 取消 ";

$msg["new_thread"] = "在新標題下撰寫留言";
$msg["your_msg_new_subject"] = "您的留言";
$msg["your_msg_on_subject"] = "留言在此標題內-";

$msg["close_win"] = "關閉視窗";
$msg["full_list"] = "所有標題";

$msg["continue_thread"] = "回覆";
$msg["open_subthread"]  = "產生子標題";

$msg["name"] = "您的姓名";
$msg["enter_name"] = "請輸入您的姓名";
$msg["enter_subj"] = "請輸入留言的標題";

$msg["view_article"] = "列出標題名稱";

$msg["all"] = "所有";
$msg["view_articles_for_last"] = "列出過去標題";
$msg["days"] = "天前";
$msg["go"] = " 執行 ";

$msg["all_articles"] = "所有標題";

$msg["remote_host"] = "遠端主機名稱";
$msg["remote_addr"] = "遠端IP位址";
$msg["proxy_addr"]  = "代理伺服器後的位址";

$msg["search"] = "搜尋";

$msg["any"] = "任一";
$msg["all"] = "所有";
$msg["exact"] = "精確";
$msg["keywords"] = "關鍵字";

$msg["tot_found"] = "所有找到資料";

$msg["stats"] = "狀態";
$msg["noread"] = "未曾閱讀";

$msg["ch_timeframe"] = "更改時間標記";
$msg["st_date"] = "開始日期";
$msg["en_date"] = "結束日期";
$msg["tot_vis"] = "查閱總次數";
$msg["host"] = "主機";
$msg["date_visit"] = "日期";

$msg["back"] = "退回";

$msg["views"] = "檢視";

$msg["all_thread_articles"] = "檢視所有標題名稱";
//////Modify by Kylin from Taiwan <kylin@netvigator.com.tw>
$msg["Delete_selected_messages"]="刪起c瓵駻靰滲d灶";
$msg["really_delete"] = "Really want to delete messages?";

?>