<?

$msg["author"] = "Auteur";
$msg["date"]   = "Datum";
$msg["subject"]   = "Onderwerp";

$msg["msg_text"]  = "Inhoud";
$msg["send_msg"] = "Verstuur";
$msg["reset_msg"] = "Verwijder";
$msg["orig_msg_text"] = "Citeer orginele tekst";
$msg["cancel"] = " annuleren ";

$msg["new_thread"] = "Begin Nieuw onderwerp";
$msg["your_msg_new_subject"] = "Uw bericht";
$msg["your_msg_on_subject"] = "Uw bericht in thread ";

$msg["close_win"] = "Sluit venster";
$msg["full_list"] = "Alle berichten";

$msg["continue_thread"] = "Reageren";
$msg["open_subthread"]  = "Maak sub-tread";

$msg["name"] = "Uw naam";
$msg["enter_name"] = "Naam";
$msg["enter_subj"] = "Onderwerp";

$msg["view_article"] = "Toon bericht";

$msg["all"] = "allemaal";
$msg["view_articles_for_last"] = "Toon berichten van de laatste";
$msg["days"] = "dagen";
$msg["go"] = " Uitvoeren ";

$msg["all_articles"] = "Alle berichten";

$msg["remote_host"] = "Remote Host";
$msg["remote_addr"] = "Remote IP address";
$msg["proxy_addr"]  = "Address behind proxy";

$msg["search"] = "Zoek";

$msg["any"] = "any";
$msg["all"] = "all";
$msg["exact"] = "exact";
$msg["keywords"] = "Zoek criteria";

$msg["tot_found"] = "Totaal aantal gevonden berichten";

$msg["stats"] = "Statistieken";
$msg["noread"] = "Ongelezen";

$msg["ch_timeframe"] = "Verander de tijdzone";
$msg["st_date"] = "Start datum";
$msg["en_date"] = "Eind datum";
$msg["tot_vis"] = "Aantal bezoeken";
$msg["host"] = "Host";
$msg["date_visit"] = "Datum";

$msg["back"] = "Terug";

$msg["views"] = "Weergave";

$msg["all_thread_articles"] = "Toon alle berichten in thread";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>