<?

$msg["author"] = "Forfatter";
$msg["date"]   = "Dato";
$msg["subject"]   = "Emne";

$msg["msg_text"]  = "Meldings-teksten";
$msg["send_msg"] = "Send melding";
$msg["reset_msg"] = "Slett melding";
$msg["orig_msg_text"] = "Sett inn original melding";
$msg["cancel"] = " Avbryt ";

$msg["new_thread"] = "Ny melding";
$msg["your_msg_new_subject"] = "Meldingen din";
$msg["your_msg_on_subject"] = "Din melding i tråden ";

$msg["close_win"] = "Lukk vindu";
$msg["full_list"] = "Alle meldinger";

$msg["continue_thread"] = "Svar";
$msg["open_subthread"]  = "Lag undertråd";

$msg["name"] = "Ditt navn";
$msg["enter_name"] = "Skriv inn navnet ditt";
$msg["enter_subj"] = "Skriv inn emnet";

$msg["view_article"] = "Se på melding";

$msg["all"] = "alle";
$msg["view_articles_for_last"] = "Se meldinger for de siste";
$msg["days"] = "dagene";
$msg["go"] = " Kjør ";

$msg["all_articles"] = "Alle meldingene";

$msg["remote_host"] = "Annen maskin";
$msg["remote_addr"] = "Maskinens ip-adresse";
$msg["proxy_addr"]  = "Addresse bak proxy-tjener";

$msg["search"] = "Søk";

$msg["any"] = "noen";
$msg["all"] = "alle";
$msg["exact"] = "eksakt";
$msg["keywords"] = "Nøkkelord";

$msg["tot_found"] = "Antall meldinger funnet";

$msg["stats"] = "Statistikk";
$msg["noread"] = "Ingen har lest";

$msg["ch_timeframe"] = "Endre tids-ramme";
$msg["st_date"] = "Start-dato";
$msg["en_date"] = "Slutt-dato";
$msg["tot_vis"] = "Totalt antall besøkende";
$msg["host"] = "Maskin";
$msg["date_visit"] = "Dato";

$msg["back"] = "Tilbake";

$msg["views"] = "Antall ganger lest";

$msg["all_thread_articles"] = "Se alle meldinger i tråden";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>