<?php

$msg["author"] = "Autor";
$msg["date"]   = "Data";
$msg["subject"]   = "Assunto";

$msg["msg_text"]  = "Texto da mensagem";
$msg["send_msg"] = "Enviar";
$msg["reset_msg"] = "Limpar";
$msg["orig_msg_text"] = "Citar original";
$msg["cancel"] = " Cancelar ";

$msg["new_thread"] = "Criar nova discussão";
$msg["your_msg_new_subject"] = "Sua mensagem";
$msg["your_msg_on_subject"] = "Sua mensagem na discussão ";

$msg["close_win"] = "Fechar janela";
$msg["full_list"] = "Todas as mensagens";

$msg["continue_thread"] = "Responder";
$msg["open_subthread"]  = "Subdividir discussão";

$msg["name"] = "Seu nome";
$msg["enter_name"] = "Por favor, digite seu nome";
$msg["enter_subj"] = "Por favor, digite o assunto da mensagem";

$msg["view_article"] = "Ver artigo";

$msg["all"] = "tudo";
$msg["view_articles_for_last"] = "Ver mensagens dos últimos";
$msg["days"] = "dias";
$msg["go"] = " Vai ";

$msg["all_articles"] = "Todas as mensagens";

$msg["remote_host"] = "Servidor Remoto";
$msg["remote_addr"] = "Endereço IP remoto";
$msg["proxy_addr"]  = "Endereço mediante proxy";

$msg["search"] = "Procurar";

$msg["any"] = "qualquer";
$msg["all"] = "todos";
$msg["exact"] = "exato";
$msg["keywords"] = "Palavras-chave";

$msg["tot_found"] = "Total de registros encontrados";

$msg["stats"] = "Estados";
$msg["noread"] = "Ninguém leu";

$msg["ch_timeframe"] = "Mudar data";
$msg["st_date"] = "Iniciar data";
$msg["en_date"] = "Finalizar data";
$msg["tot_vis"] = "Total de visitas";
$msg["host"] = "Servidor";
$msg["date_visit"] = "Data";

$msg["back"] = "Voltar";

$msg["views"] = "Visões";

$msg["all_thread_articles"] = "Todas as mensagens nessa discussão";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>