<?

$msg["author"] = "Auteur";
$msg["date"]   = "Date";
$msg["subject"]   = "Sujet";

$msg["msg_text"]  = "Texte du message";
$msg["send_msg"] = "Envoyer un message";
$msg["reset_msg"] = "Nettoyer le message";
$msg["orig_msg_text"] = "Reprendre le texte original";
$msg["cancel"] = " Annuler ";

$msg["new_thread"] = "Commencer un nouveau sujet";
$msg["your_msg_new_subject"] = "Votre message";
$msg["your_msg_on_subject"] = "Votre message dans le sujet ";

$msg["close_win"] = "Fermer la fenêtre";
$msg["full_list"] = "Tous les articles";

$msg["continue_thread"] = "Répondre";
$msg["open_subthread"]  = "Créer un sous-sujet";

$msg["name"] = "Votre nom";
$msg["enter_name"] = "Entrez votre nom";
$msg["enter_subj"] = "Entrez le sujet de votre message";

$msg["view_article"] = "Voir l'article";

$msg["all"] = "tous";
$msg["view_articles_for_last"] = "Voir les articles des derniers";
$msg["days"] = "jours";
$msg["go"] = " Aller ";

$msg["all_articles"] = "Tous les articles";

$msg["remote_host"] = "Machine distante";
$msg["remote_addr"] = "IP distante";
$msg["proxy_addr"]  = "Addresse derrière le proxy";

$msg["search"] = "Rechercher";

$msg["any"] = "un";
$msg["all"] = "tous";
$msg["exact"] = "exact";
$msg["keywords"] = "Mots-clés";

$msg["tot_found"] = "Total des résultats trouvés";

$msg["stats"] = "Stats";
$msg["noread"] = "Personne n'a lu";

$msg["ch_timeframe"] = "Changer l'intervalle des dates";
$msg["st_date"] = "Date de début";
$msg["en_date"] = "Date de fin";
$msg["tot_vis"] = "Total des visites";
$msg["host"] = "Serveur";
$msg["date_visit"] = "Date";

$msg["back"] = "Retour";

$msg["views"] = "Vues";

$msg["all_thread_articles"] = "Voir tous les articles du sujet";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>