<?
//Koi8-r

$msg["author"] = "Автор";
$msg["date"]   = "Дата";
$msg["subject"]   = "Тема";

$msg["msg_text"]  = "Текст сообщения";
$msg["send_msg"] = "Отправить сообщение";
$msg["reset_msg"] = "Очистить сообщение";
$msg["orig_msg_text"] = "Текст исходного сообщения";
$msg["cancel"] = " Отмена ";

$msg["new_thread"] = "Создать сообщение с новой темой";
$msg["your_msg_new_subject"] = "Ваше сообщение на новую тему";
$msg["your_msg_on_subject"] = "Ваше сообщение на тему";

$msg["close_win"] = "Закрыть окно";
$msg["full_list"] = "Полный список";

$msg["continue_thread"] = "Ответить";
$msg["open_subthread"]  = "Открыть подтему";

$msg["name"] = "Ваше имя";
$msg["enter_name"] = "Введите, пожалуйста, ваше имя";
$msg["enter_subj"] = "Введите, пожалуйста, тему сообщения";

$msg["view_article"] = "Просмотр статьи";

$msg["all"] = "все";
$msg["view_articles_for_last"] = "Просмотр сообщений за последние";
$msg["days"] = "дней";
$msg["go"] = "Перейти";

$msg["all_articles"] = "Все сообщения";

$msg["remote_host"] = "Удаленный хост";
$msg["remote_addr"] = "Удаленный IP адрес";
$msg["proxy_addr"] = "Обслуженный через PROXY адрес";

$msg["search"] = "Поиск";

$msg["any"] = "любые";
$msg["all"] = "все";
$msg["exact"] = "точный поиск";
$msg["keywords"] = "Ключевые слова";

$msg["tot_found"] = "Всего найдено записей";

$msg["stats"] = "Статистика";
$msg["noread"] = "Никто не читал";

$msg["ch_timeframe"] = "Изменить период";
$msg["st_date"] = "Начальная дата";
$msg["en_date"] = "Конечная дата";
$msg["tot_vis"] = "Всего обращений";
$msg["host"] = "Хост";
$msg["date_visit"] = "Время обращения";

$msg["back"] = "Назад";

$msg["views"] = "Просмотры";

$msg["all_thread_articles"] = "Просмотр всех сообщений по данной теме";

$msg["Delete_selected_messages"] = "Удалить выбранные сообщения";

$msg["really_delete"] = "Вы действительно хотите удалить сообщения?";

?>