<?php

$msg["author"] = "Forfatter";
$msg["date"]   = "Dato";
$msg["subject"]   = "Emne";

$msg["msg_text"]  = "Tekst";
$msg["send_msg"] = "Send tekst";
$msg["reset_msg"] = "Ryd tekst";
$msg["orig_msg_text"] = "Quote original tekst";
$msg["cancel"] = " Afbryd ";

$msg["new_thread"] = "Opret ny tråd";
$msg["your_msg_new_subject"] = "Din besked";
$msg["your_msg_on_subject"] = "Din besked i tråden ";

$msg["close_win"] = "Luk vindue";
$msg["full_list"] = "Fuld liste";

$msg["continue_thread"] = "Besvar";
$msg["open_subthread"]  = "Opret undertråd";

$msg["name"] = "Dit navn";
$msg["enter_name"] = "Indtast navn";
$msg["enter_subj"] = "Instast emne";

$msg["view_article"] = "Læs indlæg";

$msg["all"] = "alle";
$msg["view_articles_for_last"] = "Læs de sidste";
$msg["days"] = "dages indlæg";
$msg["go"] = " Fortsæt ";

$msg["all_articles"] = "Alle artikler";

$msg["remote_host"] = "Fjern maskine";
$msg["remote_addr"] = "Fjern IP addresse";
$msg["proxy_addr"]  = "Proxy adresse";

$msg["search"] = "Søg";

$msg["any"] = "vilkårlige";
$msg["all"] = "alle";
$msg["exact"] = "eksakt";
$msg["keywords"] = "søgeord";

$msg["tot_found"] = "Total antal indlæg fundet";

$msg["stats"] = "Statistikker";
$msg["noread"] = "Ingen har læst";

$msg["ch_timeframe"] = "Change timeframe";
$msg["st_date"] = "Start dato";
$msg["en_date"] = "Slut dato";
$msg["tot_vis"] = "Total besøgende";
$msg["host"] = "Vært";
$msg["date_visit"] = "Dato";

$msg["back"] = "Tilbage";

$msg["views"] = "Views";

$msg["all_thread_articles"] = "Læs alle indlæg i tråden";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>