<?

$msg["author"] = "Autore";
$msg["date"]   = "Data";
$msg["subject"]   = "Oggetto";

$msg["msg_text"]  = "Testo del messaggio";
$msg["send_msg"] = "Invia messaggio";
$msg["reset_msg"] = "Cancella messaggio";
$msg["orig_msg_text"] = "Cita il testo originale";
$msg["cancel"] = " Annulla ";

$msg["new_thread"] = "Crea un messaggio in una nuova discussione";
$msg["your_msg_new_subject"] = "Il tuo messaggo";
$msg["your_msg_on_subject"] = "Il tuo messaggio nella discussione";

$msg["close_win"] = "Chiudi la finestra";
$msg["full_list"] = "Tutti gli articoli";

$msg["continue_thread"] = "Rispondi";
$msg["open_subthread"]  = "Crea una sottodiscussione";

$msg["name"] = "Nome";
$msg["enter_name"] = "Inserisci il tuo nome";
$msg["enter_subj"] = "Inserisci l'oggetto del messaggio";

$msg["view_article"] = "Vedi articolo";

$msg["all"] = "Tutti";
$msg["view_articles_for_last"] = "Vedi gli articoli per gli ultimi";
$msg["days"] = "giorni";
$msg["go"] = " Vai ";

$msg["all_articles"] = "Tutti gli articoli";

$msg["remote_host"] = "Host Remoto";
$msg["remote_addr"] = "Indirizzo IP Remoto";
$msg["proxy_addr"]  = "Indirizzo dietro al proxy";

$msg["search"] = "Cerca";

$msg["any"] = "qualsiasi";
$msg["all"] = "tutti";
$msg["exact"] = "esatto";
$msg["keywords"] = "Parole chiave";

$msg["tot_found"] = "Documenti trovati";

$msg["stats"] = "Statistiche";
$msg["noread"] = "Nessuo ha letto";

$msg["ch_timeframe"] = "Change timeframe";
$msg["st_date"] = "Data di inizio";
$msg["en_date"] = "Data di fine";
$msg["tot_vis"] = "Visite totali";
$msg["host"] = "Host";
$msg["date_visit"] = "Data";

$msg["back"] = "Indietro";

$msg["views"] = "Viste";

$msg["all_thread_articles"] = "Vedi tutti gli articoli della discussione";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>