<?php

$msg["author"] = "Szerzõ";
$msg["date"]   = "Dátum";
$msg["subject"]   = "Tárgy";

$msg["msg_text"]  = "Message text";
$msg["send_msg"] = "Üzenet elkÜldése";
$msg["reset_msg"] = "Üzenet törlése";
$msg["orig_msg_text"] = "Beidézni az eredeti szöveget";
$msg["cancel"] = " Mégsem ";

$msg["new_thread"] = "Új üzenet új témában ";
$msg["your_msg_new_subject"] = "A te üzeneted";
$msg["your_msg_on_subject"] = "A te üzeneted a témában";

$msg["close_win"] = "Ablak becsukása";
$msg["full_list"] = "Ölsszes cikk";

$msg["continue_thread"] = "Válaszolni";
$msg["open_subthread"]  = "Új téma létrehozása ";

$msg["name"] = "Neved";
$msg["enter_name"] = "Légyszíves írd be a neved";
$msg["enter_subj"] = "Légyszíves írjál be tárgyat az üzenethez";

$msg["view_article"] = "Üzenet megtekintése";

$msg["all"] = "mind";
$msg["view_articles_for_last"] = "Utolsó üznetek megtekintése";
$msg["days"] = " nap";
$msg["go"] = " Mehet ";

$msg["all_articles"] = "Összes üzenet";

$msg["remote_host"] = "Távoli Gép";
$msg["remote_addr"] = "Távoli IP cím";
$msg["proxy_addr"]  = "Proxy mögötti cím";

$msg["search"] = "Keresni";

$msg["any"] = "bármelyik";
$msg["all"] = "mind";
$msg["exact"] = "pontosan";
$msg["keywords"] = "Kulcsszavak";

$msg["tot_found"] = "Talált üzenetek száma";

$msg["stats"] = "Statisztikák";
$msg["noread"] = "Senki nem olvasta";

$msg["ch_timeframe"] = "Idõintervallum megváltoztatása";
$msg["st_date"] = "Intervallum kezdete";
$msg["en_date"] = "Intervallum vége";
$msg["tot_vis"] = "Összes megtekintõ";
$msg["host"] = "Gépnév";
$msg["date_visit"] = "Dátum";

$msg["back"] = "Vissza";

$msg["views"] = "Megtekintõ";

$msg["all_thread_articles"] = "Összes üzenet megtekintése a témában";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";


?>