<?

$msg["author"] = "Pengirim";
$msg["date"]   = "Tanggal/Jam";
$msg["subject"]   = "Subyek";

$msg["msg_text"]  = "Masukkan komentar Anda";
$msg["send_msg"] = "Kirim komentar";
$msg["reset_msg"] = "Hapus komentar";
$msg["orig_msg_text"] = "Sertakan komentar asal";
$msg["cancel"] = " Batal ";

$msg["new_thread"] = "Tambahkan komentar dengan subyek baru";
$msg["your_msg_new_subject"] = "Komentar Anda";
$msg["your_msg_on_subject"] = "Komentar Anda di subyek";

$msg["close_win"] = "Tutup window ini";
$msg["full_list"] = "Semua List";

$msg["continue_thread"] = "Tanggapan";
$msg["open_subthread"]  = "Tambahkan sub-subyek";

$msg["name"] = "Nama Anda";
$msg["enter_name"] = "Silakan masukkan nama Anda";
$msg["enter_subj"] = "Silakan masukkan subyek untuk komentar Anda";

$msg["view_article"] = "Lihat artikel";

$msg["all"] = "semua";
$msg["view_articles_for_last"] = "Lihat artikel selama";
$msg["last"] = "terakhir";
$msg["days"] = "hari";
$msg["go"] = " Lihat ";

$msg["all_articles"] = "List semua artikel";

$msg["remote_host"] = "Remote Host";
$msg["remote_addr"] = "Remote IP";
$msg["proxy_addr"]  = "Alamat di bawah proxy";

$msg["search"] = "Cari";

$msg["any"] = "beberapa kata";
$msg["all"] = "semua artikel";
$msg["exact"] = "tepat kata itu";
$msg["keywords"] = "Kata kunci";

$msg["tot_found"] = "Total rekod yang ditemukan";

$msg["stats"] = "Statistik";
$msg["noread"] = "Tidak seorangpun yang membaca";

$msg["ch_timeframe"] = "Ubah selang waktu";
$msg["st_date"] = "Tanggal awal";
$msg["en_date"] = "Tanggal akhir";
$msg["tot_vis"] = "Total kunjungan";
$msg["host"] = "Host";
$msg["date_visit"] = "Tanggal/Jam";

$msg["back"] = "Kembali";

$msg["views"] = "Jumlah";

$msg["all_thread_articles"] = "Lihat semua artikel di subyek";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>