<?

$msg["author"] = "Autor";
$msg["date"]   = "Fecha";
$msg["subject"]   = "Asunto";

$msg["msg_text"]  = "Texto del mensaje";
$msg["send_msg"] = "Enviar mensaje";
$msg["reset_msg"] = "Reiniciar mensaje";
$msg["orig_msg_text"] = "Incluir texto original";
$msg["cancel"] = " Cancelar ";

$msg["new_thread"] = "Crear nuevo mensaje en el hilo";
$msg["your_msg_new_subject"] = "Su mensaje";
$msg["your_msg_on_subject"] = "Su mensaje en el hilo ";

$msg["close_win"] = "Cerrar ventana";
$msg["full_list"] = "Todos los artículos";

$msg["continue_thread"] = "Responder";
$msg["open_subthread"]  = "Crear sub-hilo";

$msg["name"] = "Su nombre";
$msg["enter_name"] = "Introduzca su nombre";
$msg["enter_subj"] = "introduzca el asunto del mensaje";

$msg["view_article"] = "Ver artículo";

$msg["all"] = "todo";
$msg["view_articles_for_last"] = "Ver artículos de los últimos";
$msg["days"] = "días";
$msg["go"] = " Ir ";

$msg["all_articles"] = "Todos los artículos";

$msg["remote_host"] = "Ordenador Remoto";
$msg["remote_addr"] = "Dirección IP remota";
$msg["proxy_addr"]  = "Dirección mediante proxy";

$msg["search"] = "Buscar";

$msg["any"] = "cualquier";
$msg["all"] = "todos";
$msg["exact"] = "exacto";
$msg["keywords"] = "Palabras clave";

$msg["tot_found"] = "Registros totales encontrados";

$msg["stats"] = "Estados";
$msg["noread"] = "No leídos";

$msg["ch_timeframe"] = "Cambiar fecha";
$msg["st_date"] = "Fecha inicio";
$msg["en_date"] = "Fecha fin";
$msg["tot_vis"] = "Visitas totales";
$msg["host"] = "Ordenador";
$msg["date_visit"] = "Fecha";

$msg["back"] = "Atrás";

$msg["views"] = "Vistas";

$msg["all_thread_articles"] = "Ver todos los artículos en el hilo";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>