<?

$msg["author"] = "Autor";
$msg["date"]   = "Datum";
$msg["subject"]   = "Betreff";

$msg["msg_text"]  = "Nachricht";
$msg["send_msg"] = "Nachricht senden";
$msg["reset_msg"] = "Zurücksetzen";
$msg["orig_msg_text"] = "Original Text quoten";
$msg["cancel"] = " Abbrechen ";

$msg["new_thread"] = "Neue Nachricht";
$msg["your_msg_new_subject"] = "Ihre Nachricht";
$msg["your_msg_on_subject"] = "Ihre Nachricht in dieser Gruppe ";

$msg["close_win"] = "Fenster schliessen";
$msg["full_list"] = "Alle Artikel";

$msg["continue_thread"] = "Antworten";
$msg["open_subthread"]  = "Erzeuge Untergruppe";

$msg["name"] = "Ihr Name";
$msg["enter_name"] = "Bitte geben Sie Ihren Namen ein";
$msg["enter_subj"] = "Bitte geben Sie den Betreff der Nachricht ein";

$msg["view_article"] = "Artikel lesen";

$msg["all"] = "Alle";
$msg["view_articles_for_last"] = "Die letzten Artikel lesen";
$msg["days"] = "Tage";
$msg["go"] = " Start ";

$msg["all_articles"] = "Alle Artikel";

$msg["remote_host"] = "Remote Rechner";
$msg["remote_addr"] = "Remote IP Adresse";
$msg["proxy_addr"]  = "Adresse hinter Proxy";

$msg["search"] = "Suchen";

$msg["any"] = "Einige";
$msg["all"] = "Alle";
$msg["exact"] = "Exakt";
$msg["keywords"] = "Schlüsselwörter";

$msg["tot_found"] = "Total Einträge gefunden";

$msg["stats"] = "Statistik";
$msg["noread"] = "Niemand hat gelesen";

$msg["ch_timeframe"] = "Zeitraum ändern";
$msg["st_date"] = "Start Datum";
$msg["en_date"] = "End Datum";
$msg["tot_vis"] = "Total Besucher";
$msg["host"] = "Rechner";
$msg["date_visit"] = "Datum";

$msg["back"] = "zurück";

$msg["views"] = "Ansichten";

$msg["all_thread_articles"] = "Alle Artikel zu diesem Thema lesen";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";


?>