<?

$msg["author"] = "Autor";
$msg["date"]   = "Data";
$msg["subject"]   = "Assunto";

$msg["msg_text"]  = "Texto da Mensagem";
$msg["send_msg"] = "Enviar Mensagem";
$msg["reset_msg"] = "Apagar mensagem";
$msg["orig_msg_text"] = "Incluir texto original";
$msg["cancel"] = " Cancelar ";

$msg["new_thread"] = "Criar mensagem em novo tópico";
$msg["your_msg_new_subject"] = "Sua mensagem";
$msg["your_msg_on_subject"] = "Sua mensagem no tópico ";

$msg["close_win"] = "Fechar janela";
$msg["full_list"] = "Todos os artigos";

$msg["continue_thread"] = "Responder";
$msg["open_subthread"]  = "Criar sub-tópico";

$msg["name"] = "Seu nome";
$msg["enter_name"] = "Por favor entre com seu nome";
$msg["enter_subj"] = "Por favor entre com o assunto da mensagem";

$msg["view_article"] = "Visualizar artigo";

$msg["all"] = "todos";
$msg["view_articles_for_last"] = "Visualizar artigos dos últimos";
$msg["days"] = "dias";
$msg["go"] = " executar ";

$msg["all_articles"] = "Todos os artigos";

$msg["remote_host"] = "Servidor remoto";
$msg["remote_addr"] = "EndereÚo IP remoto";
$msg["proxy_addr"]  = "Endereço por trás do proxy";

$msg["search"] = "Busca";

$msg["any"] = "qualquer uma";
$msg["all"] = "todas";
$msg["exact"] = "exatamente";
$msg["keywords"] = "Palavras-chave";

$msg["tot found"] = "Quantidade de mensagens encontradas: ";

$msg["stats"] = "Status";
$msg["noread"] = "Não lidas";

$msg["ch_timeframe"] = "Mudar datas";
$msg["st_date"] = "Data de inicio";
$msg["en_date"] = "Data de término";
$msg["tot_vis"] = "Total de visitas";
$msg["host"] = "Servidor";
$msg["date_visit"] = "Data";

$msg["back"] = "Voltar";

$msg["views"] = "Vistas";

$msg["all_thread_articles"] = "Visualizar todos os artigos no tópico";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>