<?

$msg["author"] = "Autor";
$msg["date"]   = "Data";
$msg["subject"]   = "Temat";

$msg["msg_text"]  = "Tre¶æ wiadomo¶ci";
$msg["send_msg"] = "Wy¶lij wiadomo¶æ";
$msg["reset_msg"] = "Wyczy¶æ wiadomo¶æ";
$msg["orig_msg_text"] = "Cytuj orginalny tekst";
$msg["cancel"] = " Anuluj ";

$msg["new_thread"] = "Nowa wiadomo¶æ";
$msg["your_msg_new_subject"] = "Twoja wiadomo¶æ";
$msg["your_msg_on_subject"] = "Twoja wiadomo¶æ w w±tku ";

$msg["close_win"] = "Zamknij okno";
$msg["full_list"] = "Wszystkie artyku³y";

$msg["continue_thread"] = "Odpowiedz";
$msg["open_subthread"]  = "Stwórz podw±tek";

$msg["name"] = "Twoje imiê";
$msg["enter_name"] = "Wpisz swoje imiê";
$msg["enter_subj"] = "Wpisz temat wiadomo¶ci";

$msg["view_article"] = "Zobacz artyku³";

$msg["all"] = "wszystkie";
$msg["view_articles_for_last"] = "Poka¿ wiadomo¶ci z ostatnich ";
$msg["days"] = "dni";
$msg["go"] = " Id¼ ";

$msg["all_articles"] = "Wszystkie artyku³y";

$msg["remote_host"] = "Zdalny host";
$msg["remote_addr"] = "Zdalny adres IP";
$msg["proxy_addr"]  = "Adres za proxy";

$msg["search"] = "Szukaj";

$msg["any"] = "dowolne";
$msg["all"] = "wszystkie";
$msg["exact"] = "dok³adnie";
$msg["keywords"] = "S³owa kluczowe";

$msg["tot_found"] = "Znalezionych rekordów";

$msg["stats"] = "Statystyki";
$msg["noread"] = "Nikt nie przeczyta³";

$msg["ch_timeframe"] = "Zmieñ przdzia³ czasowy";
$msg["st_date"] = "Data pocz±tkowa";
$msg["en_date"] = "Data koñcowa";
$msg["tot_vis"] = "Razem wizyt";
$msg["host"] = "Host";
$msg["date_visit"] = "Data";

$msg["back"] = "Wstecz";

$msg["views"] = "Ods³on";

$msg["all_thread_articles"] = "Poka¿ wszystkie artyku³y w w±tku";

$msg["Delete_selected_messages"] = "Delete selected messages";

$msg["really_delete"] = "Really want to delete messages?";

?>